class AddCellsBody < ActiveRecord::Migration[6.1]
  def change
    add_column :cells, :body14, :string
    add_column :cells, :body15, :string
    add_column :cells, :body16, :string
    add_column :cells, :body17, :string
    add_column :cells, :body18, :string
    add_column :cells, :body19, :string
    add_column :cells, :body21, :string
    add_column :cells, :body22, :string
    add_column :cells, :body23, :string
    add_column :cells, :body24, :string
    add_column :cells, :body25, :string
    add_column :cells, :body26, :string
    add_column :cells, :body27, :string
    add_column :cells, :body28, :string
    add_column :cells, :body29, :string
    add_column :cells, :body31, :string
    add_column :cells, :body32, :string
    add_column :cells, :body33, :string
    add_column :cells, :body34, :string
    add_column :cells, :body35, :string
    add_column :cells, :body36, :string
    add_column :cells, :body37, :string
    add_column :cells, :body38, :string
    add_column :cells, :body39, :string
    add_column :cells, :body41, :string
    add_column :cells, :body42, :string
    add_column :cells, :body43, :string
    add_column :cells, :body44, :string
    add_column :cells, :body45, :string
    add_column :cells, :body46, :string
    add_column :cells, :body47, :string
    add_column :cells, :body48, :string
    add_column :cells, :body49, :string
    add_column :cells, :body51, :string
    add_column :cells, :body52, :string
    add_column :cells, :body53, :string
    add_column :cells, :body54, :string
    add_column :cells, :body55, :string
    add_column :cells, :body56, :string
    add_column :cells, :body57, :string
    add_column :cells, :body58, :string
    add_column :cells, :body59, :string
    add_column :cells, :body61, :string
    add_column :cells, :body62, :string
    add_column :cells, :body63, :string
    add_column :cells, :body64, :string
    add_column :cells, :body65, :string
    add_column :cells, :body66, :string
    add_column :cells, :body67, :string
    add_column :cells, :body68, :string
    add_column :cells, :body69, :string
    add_column :cells, :body71, :string
    add_column :cells, :body72, :string
    add_column :cells, :body73, :string
    add_column :cells, :body74, :string
    add_column :cells, :body75, :string
    add_column :cells, :body76, :string
    add_column :cells, :body77, :string
    add_column :cells, :body78, :string
    add_column :cells, :body79, :string
    add_column :cells, :body81, :string
    add_column :cells, :body82, :string
    add_column :cells, :body83, :string
    add_column :cells, :body84, :string
    add_column :cells, :body85, :string
    add_column :cells, :body86, :string
    add_column :cells, :body87, :string
    add_column :cells, :body88, :string
    add_column :cells, :body89, :string
    add_column :cells, :body91, :string
    add_column :cells, :body92, :string
    add_column :cells, :body93, :string
    add_column :cells, :body94, :string
    add_column :cells, :body95, :string
    add_column :cells, :body96, :string
    add_column :cells, :body97, :string
    add_column :cells, :body98, :string
    add_column :cells, :body99, :string
  end
end
